# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d9987e31e33e164911e5f341e17945943066fbe5eb7517341d1633a96f0792826fc5b8261d6126de3196b88070a4ee65c49f811cdc636c6473286d1927d3893

test:
  secret_key_base: 1ffb470a6834af4b1e3b0cabcb78a5f60fa248c3206725e6a64fa19189de166ff71071aadd2d3458cff4c4328577515ca6ff93ac2b10299268ad35136696c475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4da02e273cd123a7fa91ba95632a21ce38bb912bae16498a79319ca5c5d9c2339d2bfd7b078fc5177aaf69f95b59bbdc22486d589fd658bd50528136d9073a53
